/**
 * genEmoji.cjs — one-time generator for the full emoji dataset used by
 * <EmojiPicker>. Merges emojibase-data (English labels/tags + grouping) with
 * CLDR Hebrew annotations into a compact, committed src/data/emoji.ts so the
 * heavy source packages don't ship in the app bundle.
 *
 * To regenerate:
 *   npm i -D emojibase-data cldr-annotations-full
 *   node scripts/genEmoji.cjs
 *   npm uninstall emojibase-data cldr-annotations-full
 */
const fs = require("fs");
const path = require("path");

const en = require("emojibase-data/en/data.json");
const heAnn = require("cldr-annotations-full/annotations/he/annotations.json")
  .annotations.annotations;

// Hebrew labels for emojibase group ids (group 2 = "component" is skipped).
const GROUP_HE = {
  0: "פרצופים",
  1: "אנשים",
  3: "חיות וטבע",
  4: "אוכל",
  5: "מקומות",
  6: "פעילויות",
  7: "חפצים",
  8: "סמלים",
  9: "דגלים",
};

const rows = [];
for (const e of en) {
  if (e.group == null || e.group === 2) continue; // skip skin-tone/hair components
  const enKw = [e.label, ...(e.tags || [])];
  const he = heAnn[e.emoji];
  const heKw = he ? [...(he.default || []), ...(he.tts || [])] : [];
  rows.push({
    c: e.emoji,
    g: e.group,
    o: e.order ?? 0,
    k: [...enKw, ...heKw].join(" ").toLowerCase(),
  });
}
rows.sort((a, b) => a.g - b.g || a.o - b.o);

const emojis = rows.map(({ c, g, k }) => ({ c, g, k }));
const groups = Object.entries(GROUP_HE).map(([id, label]) => ({
  id: Number(id),
  label,
}));

const ts = `// AUTO-GENERATED by scripts/genEmoji.cjs — do not edit by hand.
// Full Unicode emoji set with English + Hebrew (CLDR) search keywords.
export interface EmojiEntry {
  /** the emoji character */
  c: string;
  /** emojibase group id (see EMOJI_GROUPS) */
  g: number;
  /** lowercased English + Hebrew keywords for search */
  k: string;
}
export const EMOJI_GROUPS: { id: number; label: string }[] = ${JSON.stringify(groups)};
export const EMOJI_DATA: EmojiEntry[] = ${JSON.stringify(emojis)};
`;

const outDir = path.join(__dirname, "..", "src", "data");
fs.mkdirSync(outDir, { recursive: true });
fs.writeFileSync(path.join(outDir, "emoji.ts"), ts);
console.log(`wrote ${emojis.length} emojis across ${groups.length} groups`);
